require "json"
require "msgpack"

require "./quartz/version"
require "./quartz/types"
require "./quartz/scale"
require "./quartz/duration"
require "./quartz/time_point"
require "./quartz/event_set"
require "./quartz/time_cache"
require "./quartz/comparison"
require "./quartz/any"
require "./quartz/list"
require "./quartz/simple_hash"
require "./quartz/logging"
require "./quartz/errors"
require "./quartz/observer"
require "./quartz/hooks"
require "./quartz/verifiable"
require "./quartz/port"
require "./quartz/coupleable"
require "./quartz/coupler"
require "./quartz/transitions"
require "./quartz/schedulers"
require "./quartz/state"
require "./quartz/model"
require "./quartz/atomic"
require "./quartz/coupled"
require "./quartz/simulable"
require "./quartz/processor"
require "./quartz/simulator"
require "./quartz/coordinator"
require "./quartz/root"
# require "./quartz/dsde"
# require "./quartz/multi_component"
require "./quartz/visitor"
require "./quartz/processor_allocator"
require "./quartz/dot_visitor"
require "./quartz/direct_connection_visitor"
require "./quartz/simulation"

module Quartz
  # Returns the current version
  def self.version
    VERSION
  end
end
